language: csharp
sudo: required
dist: trusty
dotnet: 2.0.0
solution: src/NReco.Data.sln

script:
- dotnet restore src/NReco.Data.sln
- dotnet test src/NReco.Data.Tests/NReco.Data.Tests.csproj --configuration Release
